// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using WalkerFcb.Api.Data;

#nullable disable

namespace WalkerFcb.Api.Migrations
{
    [DbContext(typeof(WalkerDbContext))]
    [Migration("20260310112413_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("text")
                        .HasColumnName("amount");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_ingredients_ingredient_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_recipe_ingredients_stage_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_recipe_ingredients_unit_id");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("MadeOn")
                        .HasColumnType("date")
                        .HasColumnName("made_on");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_reviews");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_reviews_recipe_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recipe_reviews_user_id");

                    b.ToTable("recipe_reviews", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("SubRecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_stages");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_stages_recipe_id");

                    b.HasIndex("SubRecipeId")
                        .HasDatabaseName("ix_recipe_stages_sub_recipe_id");

                    b.ToTable("recipe_stages", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_steps");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_recipe_steps_stage_id");

                    b.ToTable("recipe_steps", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeTag", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("RecipeId", "TagId")
                        .HasName("pk_recipe_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tags_tag_id");

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tags_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Italian",
                            Slug = "italian"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Chinese",
                            Slug = "chinese"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Indian",
                            Slug = "indian"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Mexican",
                            Slug = "mexican"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "French",
                            Slug = "french"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Thai",
                            Slug = "thai"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Japanese",
                            Slug = "japanese"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "British",
                            Slug = "british"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Vegetarian",
                            Slug = "vegetarian"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Vegan",
                            Slug = "vegan"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Gluten-Free",
                            Slug = "gluten-free"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Dairy-Free",
                            Slug = "dairy-free"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Nut-Free",
                            Slug = "nut-free"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Weeknight",
                            Slug = "weeknight"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Weekend",
                            Slug = "weekend"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "Special Occasion",
                            Slug = "special-occasion"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "Batch Cook",
                            Slug = "batch-cook"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Quick",
                            Slug = "quick"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Spring",
                            Slug = "spring"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Summer",
                            Slug = "summer"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Name = "Autumn",
                            Slug = "autumn"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Name = "Winter",
                            Slug = "winter"
                        });
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_categories_name");

                    b.ToTable("tag_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cuisine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dietary"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Occasion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Season"
                        });
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "g",
                            Name = "gram",
                            UnitType = "mass"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "kg",
                            Name = "kilogram",
                            UnitType = "mass"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "oz",
                            Name = "ounce",
                            UnitType = "mass"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "lb",
                            Name = "pound",
                            UnitType = "mass"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "ml",
                            Name = "millilitre",
                            UnitType = "volume"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "l",
                            Name = "litre",
                            UnitType = "volume"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "tsp",
                            Name = "teaspoon",
                            UnitType = "volume"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "tbsp",
                            Name = "tablespoon",
                            UnitType = "volume"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "cup",
                            Name = "cup",
                            UnitType = "volume"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "pinch",
                            Name = "pinch",
                            UnitType = "arbitrary"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "handful",
                            Name = "handful",
                            UnitType = "arbitrary"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "to taste",
                            Name = "to taste",
                            UnitType = "arbitrary"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "x",
                            Name = "whole",
                            UnitType = "count"
                        });
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Geoff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Helen"
                        });
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.RecipeStage", "Stage")
                        .WithMany("Ingredients")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipe_ingredients_recipe_stages_stage_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipe_ingredients_units_unit_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Stage");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeReview", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.Recipe", "Recipe")
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_reviews_recipes_recipe_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_reviews_users_user_id");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeStage", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.Recipe", "Recipe")
                        .WithMany("Stages")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_stages_recipes_recipe_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.Recipe", "SubRecipe")
                        .WithMany()
                        .HasForeignKey("SubRecipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipe_stages_recipes_sub_recipe_id");

                    b.Navigation("Recipe");

                    b.Navigation("SubRecipe");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeStep", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.RecipeStage", "Stage")
                        .WithMany("Steps")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_steps_recipe_stages_stage_id");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeTag", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_recipes_recipe_id");

                    b.HasOne("WalkerFcb.Api.Data.Entities.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_tags_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Tag", b =>
                {
                    b.HasOne("WalkerFcb.Api.Data.Entities.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tag_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("RecipeTags");

                    b.Navigation("Reviews");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.RecipeStage", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.Unit", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WalkerFcb.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
